// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Comment struct {
	ID        int32      `json:"id"`
	PostID    int32      `json:"postId"`
	ParentID  *int32     `json:"parentId,omitempty"`
	Author    int32      `json:"author"`
	Content   string     `json:"content"`
	CreatedAt string     `json:"createdAt"`
	UpdatedAt string     `json:"updatedAt"`
	Replies   []*Comment `json:"replies,omitempty"`
}

type CreateCommentInput struct {
	PostID   int32  `json:"postId"`
	ParentID *int32 `json:"parentId,omitempty"`
	Content  string `json:"content"`
}

type CreatePostInput struct {
	Title         string `json:"title"`
	Content       string `json:"content"`
	AllowComments bool   `json:"allowComments"`
}

type Mutation struct {
}

type Post struct {
	ID            int32      `json:"id"`
	Title         string     `json:"title"`
	Content       string     `json:"content"`
	Author        int32      `json:"author"`
	AllowComments bool       `json:"allowComments"`
	CreatedAt     string     `json:"createdAt"`
	UpdatedAt     string     `json:"updatedAt"`
	Comments      []*Comment `json:"comments,omitempty"`
}

type Query struct {
}

type Subscription struct {
}
